title: <p align="center"> Pavan Kale </p>
logo: /assets/img/Photo.JPG
description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pavan-kale-408b7a20">LinkedIn</a> |
  <a href="https://github.com/pavankale2709">GitHub</a>
  </p>
   
  I'm working on projects involving Java (Spring, MicroServices), Perl, Python, AI & ML. 
  <br>
  
  
  
theme: jekyll-theme-minimal
