title: <p align="center"> Pavan Kale </p>
logo: /assets/img/Photo.JPG
description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pavan-kale-408b7a20">LinkedIn</a> |
  <a href="https://github.com/pavankale2709">GitHub</a>
  </p>
   
  I'm working on Java, Python, AI & ML Projects. Worked in TCS for 4.6 years on Java, Struts, Spring etc projects. Working in BMC Software for 7 years projects involving Java, Spring, Kubernetes etc 
  <br>
  
  
  
theme: jekyll-theme-minimal
